### PR TITLE
Point Shop Page 2024

### LINKED ISSUE #509: Point Shop 2024
create new branch called `sunny/point-shop-2024`

🎨 **UI Redesigns**
- [ ] implement the new mobile designs according to Figma
- [ ] user must be able to switch between viewing merch and raffle prizes

📱 **Functionality**
- [x] fetch shop data from the `GET /shop/` endpoint ([here](https://docs.hackillinois.org/#api-Shop:~:text=Copy-,Shop,-Shop%20%7C%20GET)), returns `List<ShopItem>`
- [ ] display the items in a RecyclerView (one per row), need adapter and fragment files for this (similar to setup of Leaderboard)
- [x] in the `Profile.kt` entity, add the `var coins: Int` field 
- [x] use the `ProfileRepository.kt` in `ShopViewModel` to fetch the user's coins and display them in the Point Shop
- [x] do not display coins to staff or guest users
- [x] update the `ShopRepository.kt` file and create the `ShopViewModel.kt` file that will call `fetchShop`
- [x] create new `ShopItem` model class (need `entity`, `DAO`, and add it to our Room database to be cached locally)
- [x] make API calls every ~10 seconds to refresh the shop quantities (use `TimerTask`? similar to QR code refresh on Profile page)
- [ ] **tentative:** have pop-up with instructions on how to redeem items at the hackathon if the user clicks on one of the prizes 

**can model a lot of the functionality after the already existing leaderboard files, but need way to switch between merch and raffle tabs and show the appropriate items (TabLayout possibly? can look at Schedule page code for reference as well)**

✨ **Extras**
- [ ] add refresh animation for point shop

### PR DESCRIPTION
**Pull request by leesunny790**

### CODE REVIEW

**Comment by leahlud** [comment]
nice progress! just a few notes so far:
- [x] can you modify the background and page title constraints according to [this doc](https://docs.google.com/document/d/1opqiuC9EKKjD7d4pTq08mp9Y8cyMR0pG_WcQ6SIpAmg/edit)?
- [x] `imageview_points_shop_banner` needs to be constrained horizontally in `fragment_points_shop.xml`
- [x] small thing: it's "Point Shop" instead of "Points Shop"

**Comment by leahlud** [comment]
- [x] `GET /shop/` doesn't return a JSON object of shop item objects but rather just a list of them (different than the other endpoints like `GET /event/`), so the return type of the API call should be `List<ShopItem>` - basically don't need to wrap it in a data class
- [x] need to add the new field `var imageURL: String` to `ShopItem.kt`
- [x] constrain the "Point Shop" title text view to the bottom of the guideline you added and remove the top margin of that text view
- [x] refer to [this page](https://github.com/orgs/HackIllinois/projects/13?pane=issue&itemId=43000267) for more details (updated information on getting coins)

**endpoint:** https://docs.hackillinois.org/#api-Shop-GetShop

**Review by leahlud — CHANGES_REQUESTED** [review]
**Final things:**
- [x] add click listeners to `MERCH` and `RAFFLE` tabs and filter the items being shown by their `isRaffle` field
- [x] add the brown divider after the last item in the recycler view

**Comment by leesunny790** [comment]
image
divider is shown at bottom when there are less than 4

**Review by leahlud — APPROVED** [review]

**Pull request merged**
