### PR TITLE
Changed attendee button color

### PR DESCRIPTION
**Pull request by leahlud**
* updated attendee button from midnight to sea salt green

### CODE REVIEW

**Review by leesunny790 — APPROVED** [review]
looks good!

**Review by AdityaK2905 — COMMENTED** [review]
Looks good.

**Comment by dominick-deseta** [comment]
giphy

**Review by dominick-deseta — APPROVED** [review]
giphy

**Review by AdityaK2905 — APPROVED** [review]

**Comment by leahlud** [comment]
this was a demo pull-request to show the team how things work!

**Pull request closed without merging**
