### PR TITLE
Home page redesign

### PR DESCRIPTION
**Pull request by ApoorvaAditya**

### CODE REVIEW

**Comment by rachels23** [comment]
increase the size of the "Current" and  "Upcoming" text

**Comment by leesunny790** [comment]
change banner text from "what's cookin?" to "hackillinois begins in ...", increase space between countdown and current/upcoming tab labels, increase "current" and "upcoming" font size

**Comment by leesunny790** [comment]
Screen Shot 2023-01-12 at 5 32 34 PM

**Comment by ApoorvaAditya** [comment]
The "what's cookin?" text should change once the API is updated to reflect the start timings of HackIllinois 2023 instead of HackIllinois 2022. It shows "what's cookin?" because it thinks the hackathon is already over.

**Comment by leesunny790** [comment]
increase spacing between days hours minutes

**Comment by leesunny790** [comment]
Screen Shot 2023-01-12 at 5 41 36 PM
Screen Shot 2023-01-12 at 5 42 05 PM

**Comment by leesunny790** [comment]
bold current and upcoming text (?)

**Review by rachels23 — APPROVED** [review]

**Pull request merged**
