### PR TITLE
Navbar bug fix and added last year's changes

### PR DESCRIPTION
**Pull request by leahlud**
added changes from this [pull request](https://github.com/HackIllinois/android/pull/465) that were never merged

**Test the following:**
- pressing the back button while in the scanner camera view navigates back to the staff attendance page __with the navbar__

### CODE REVIEW

**Review by AdityaK2905 — APPROVED** [review]
Swiping back out of scanner shows navbar, works as intended.

**Comment by leesunny790** [comment]
stuck on loading screen with Pixel 5 emulator, stuck on Google login screen with Pixel 2 emulator

**Review by leesunny790 — COMMENTED** [review]
stuck on loading screen in android emulator, will try again with different wifi later

**Review by dominick-deseta — APPROVED** [review]
Confirmed bug fix. Great job~! 

image

**Pull request merged**
