### PR TITLE
Leaderboard fragment

### PR DESCRIPTION
**Pull request by leesunny790**
slightly enlarged margins of leaderboard tile and made recyclerview closer to the "LEADERBOARD" title, have not tested on different screen dimensions

### CODE REVIEW

**Comment by rachels23** [comment]
- [ ] Add "pts" after the point values
- [ ] Increase padding between the "Leaderboard" text and the RecyclerView
image

**Comment by rachels23** [comment]
add a bottom layout margin of ~20dp for the recyler view to allow for scrolling + prevent the bottom nav bar from blocking any content

**Comment by KevinYan12138** [comment]
- [ ] Align the name of the 10th leader with the rest of them.

Screen Shot 2023-01-12 at 3 13 25 PM 1

**Review by rachels23 — APPROVED** [review]
leaderboard looks good

**Pull request merged**
