### PR TITLE
Version API Sync & Room Database Revamp 

### PR DESCRIPTION
**Pull request by leahlud**
* Display dialog to force users to update the app if version is less than api's version (`GET /version/android/`)
  * Version is in the format `year.version.patch` ... i.e. `"2024.1.1"`
* Updated multiple endpoints in app and the model classes to match new api
* Revamped the Room database schema, queries, and functions to match the new api
* Removed unnecessary code and files (like Projects and old api endpoints)

### CODE REVIEW

**Review by dominick-deseta — APPROVED** [review]
tested what you requested and it all works!
i think you noticed this but there is a blank screen before the loading screen for a second when loading the app with the right version

**Comment by leahlud** [comment]
yeah.. loading animation doesn't start until after version code is checked between app + api. We can talk about what would be the best flow during the meeting

**Review by AdityaK2905 — COMMENTED** [review]
App repeatedly crashes for me, not sure how it's working for Dom. Development branch runs fine, but this branch crashes for me.

**Comment by leahlud** [comment]
what specifically is crashing? and error logs?

**Review by AdityaK2905 — APPROVED** [review]
Everything works now; profile page crashes when logged in as guest however. I'll see if I can deal with that?

**Review by leesunny790 — APPROVED** [review]
image

got popup!

**Comment by leahlud** [comment]
> Everything works now; profile page crashes when logged in as guest however. I'll see if I can deal with that?

Fixed issue by checking if the user is logged in and isn't staff. App doesn't clear saved `provider` in SharedPreferences, so that's on my todo list for later on when we refactor the login flow for mentors, volunteers, etc.

**Pull request merged**
