### PR TITLE
Material design shadows

### PR DESCRIPTION
**Pull request by bstrauch24**
Changes minimum API to 21.
Will change percentage of supported users from 96.2% to 89.3%.

### CODE REVIEW

**Comment by bstrauch24** [comment]
Closes #122

**Comment by patrickfeltes** [comment]
Thanks for doing this, Brian!

Apparently, there's a way we can do this without bumping to API 21. The second answer to [this thread](https://stackoverflow.com/questions/26728570/android-appcompat-21-elevation) has a drawable that we can use. Then we can create a folder called `layouts-v21` which android will automatically use for layouts API 21+. The regular layouts folder should apply to all other versions. So we can just have two versions of the layouts that need the elevation attribute.

**Comment by bstrauch24** [comment]
Is the layouts-v21 folder necessary? Why not use the solution that works before API 21 for all versions?

**Comment by patrickfeltes** [comment]
Good point. Let's just go with the drawable.

**Pull request closed without merging**
