### PR TITLE
Schedule Page 2024

### LINKED ISSUE #507: Schedule Page 2024
create new branch called `dominick/schedule-2024`

🎨 **UI Redesigns**
- [x] add new page (fragment, tab layout?) for displaying shifts for staff login
- [x] remove favorites button/filters when "shifts" is selected
- [x] add "Pro" oval tag to event cards (and show it accordingly)
- [ ] implement the new mobile designs according to Figma
- [x] add "Ongoing" header to ongoing event

📱 **Functionality**
- [x] ensure all necessary event / shift components are displayed (shifts don't have expanded card view and aren't favoritable)
- [x] only attendees can favorite events (staff and guests should not see the bookmark icons)
- [x] labels for the hackathon dates are Febuary 23, 24, 25
- [ ] replace Google maps on event cards with static maps (_image urls will come from the API, need to parse and display them_)
- [x] shifts aren't clickable
- [ ] don't show pro-only events to non-pro attendees, but guests and pro attendees can see pro events (this should be handled by api when you make a request based on your auth)
- [ ] fetch staff shifts from the `GET /staff/shifts/` endpoint (in progress [here](https://github.com/HackIllinois/adonix/issues/128))
- [x] create new `Shift` model class (need `entity`, `DAO`, and add it to our Room database to be cached locally)
- [ ] **BUG:** if you have the favorites toggle on and open an event card, when you return to the full events page the toggle is off but only favorited events are shown

✨ **Extras**
- [ ] implement refresh animations for schedule page
- [ ] add slide up animation for opening the expanded event card views

\
\

### PR DESCRIPTION
**Pull request by dominick-deseta**
Working on UI Designs, Functionality, and Extras

### CODE REVIEW

**Comment by leahlud** [comment]
nice work so far! a few notes:

- [x] I think it would be better if the schedule/shifts labels were farther apart, can you make it so there's a `35dp` starting margin for "Schedule" and a `35dp` ending margin for "Shifts"? and get rid of the `50dp` margin you set programmatically
- [x] make the time dividers formatted like `5:00 AM`
- [x] guests should not be able to see the bookmarks either

**Comment by leahlud** [comment]
Potion tabs look awesome!! Some notes:
- [x] shifts tab should have the pink bg, and the highlighted potion should be the blue/green color
- [x] fix the kt lint errors

image

**Review by leahlud — DISMISSED** [review]
- [x] bug: if you click on an event with a pro tag, the event card doesn't retain the pro tag
- [x] add `isPro` field to event entity and display on events
- [ ] look into fragment lifecycles with event card thingy
- [x] add `mapImageUrl` field to event entity and display the map in event card expanded view
- [x] `event.sponsor` will return empty string if there is no sponsor
- [x] add padding beneath potions on schedule so when you scroll it doesn't go right up to them
- [ ] refresh animation?

**Comment by leahlud** [comment]
**issues**
- events are showing up on shifts page (first time opened)
- if logged in as attendee or guest, DONT fetch shifts

**Review by AdityaK2905 — APPROVED** [review]
AMAZING

**Review by leahlud — APPROVED** [review]
image

**Pull request merged**
